import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "./provider/AuthProvider";
import { createClient } from "@/utils/supabase/server";
import { cookies } from "next/headers";
import NavigationBar from "./components/NavigationBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

	const cookieStore = await cookies()
	const supabase = createClient(cookieStore)

	//  user from session
	const { data: { user } } = await supabase.auth.getUser();

	let fullUser = null;

	if (user) {
		const { data: profile } = await supabase
		.from("User")
		.select("*")
		.eq("id", user.id)
		.single();

		fullUser = { ...user, profile };
	}

	// console.log("SERVER USER:", fullUser)
	

	return (
		<html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
			<body className="min-h-full flex flex-col">
				<AuthProvider initialUser={fullUser}>
					<NavigationBar />
					{children}
				</AuthProvider>
				<Toaster />
			</body>
		</html>
	);
}
